FROM node:12.13-alpine

WORKDIR /app

COPY package*.json ./

# AWS RDS vars
ARG POSTGRES_USER
ARG POSTGRES_HOST
ARG POSTGRES_PORT
ARG POSTGRES_PASSWORD
ARG POSTGRES_DB

ENV POSTGRES_USER=$POSTGRES_USER
ENV POSTGRES_HOST=$POSTGRES_HOST
ENV POSTGRES_PORT=$POSTGRES_PORT
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
ENV POSTGRES_DB=$POSTGRES_DB

RUN npm install

RUN npm run build

COPY . .

CMD ["npm", "run", "start:dev"]
